routes/web.php
<?php

use App\Http\Controllers\CancelDeliveryController;
use App\Http\Controllers\CompleteDeliveriesController;
use App\Http\Controllers\DeliverOrdersController;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\ShowCampaignsController;
use App\Http\Controllers\DetailCanceledOrdersController;
use App\Http\Controllers\DetailDeliveredOrdersController;
use App\Http\Controllers\DetailPendingOrdersController;
use App\Http\Controllers\DetailProcessingOrdersController;
use App\Http\Controllers\RescheduleDeliveryController;
use App\Http\Controllers\Settings\ShowConfigSettingsController;
use App\Http\Controllers\ShowOrdersController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::middleware('auth')->group(function () {

    // Home.
    Route::get("/", ShowCampaignsController::class)
        ->name('campaigns.index');

    // Configurações.
    Route::get('/settings/configs', ShowConfigSettingsController::class)
        ->name('settings.configs');

    // Campanhas.
    Route::prefix('campanhas')
        ->name('campaigns')
        ->group(function () {

            // Estas rotas foram desativadas por não serem mais necessárias,
            // entretanto, estão ainda comentadas para caso o cliente decida
            // continuar usando.

            // // Detalhe da campanha.
            // Route::get('{campaign:slug}', DetailCampaignsController::class)
            //     ->name('.show');

            // // Setores.
            // Route::prefix('{campaign:slug}/setor/{sector}')
            //     ->name('.sectors.orders')
            //     ->group(function () {

            //         // Lista de pedidos.
            //         Route::get('pedidos', ShowSectorOrdersController::class)
            //             ->name('.index');

            //         // Entrega os pedidos de acordo com a quantidade informada.
            //         Route::post('pedidos/entregar', DeliverSectorOrdersController::class)
            //             ->name('.deliver');

            //         // Lista os pedidos em processo.
            //         Route::get('pedidos/andamento', DetailSectorProcessingOrdersController::class)
            //             ->name('.show.processing');

            //         // Lista os pedidos pendentes.
            //         Route::get('pedidos/pendentes', DetailSectorPendingOrdersController::class)
            //             ->name('.show.pending');

            //         // Lista os pedidos entregues.
            //         Route::get('pedidos/entregues', DetailSectorDeliveredOrdersController::class)
            //             ->name('.show.delivered');

            //         // Lista os pedidos cancelados.
            //         Route::get('pedidos/cancelados', DetailSectorCanceledOrdersController::class)
            //             ->name('.show.canceled');
            // });

            // Pedidos
            Route::prefix('{campaign:slug}/pedidos')
                ->name('.orders')
                ->group(function() {

                    // Lista os pedidos.
                    Route::get('', ShowOrdersController::class)
                        ->name('.index');

                    // Entrega os pedidos de acordo com a quantidade informada.
                    Route::post('entregar', DeliverOrdersController::class)
                        ->name('.deliver');

                    // Lista os pedidos em processo.
                    Route::get('andamento', DetailProcessingOrdersController::class)
                        ->name('.show.processing');

                    // Lista os pedidos pendentes.
                    Route::get('pendentes', DetailPendingOrdersController::class)
                        ->name('.show.pending');

                    // Lista os pedidos entregues.
                    Route::get('entregues', DetailDeliveredOrdersController::class)
                        ->name('.show.delivered');

                    // Lista os pedidos cancelados.
                    Route::get('cancelados', DetailCanceledOrdersController::class)
                        ->name('.show.canceled');

                });
    });

    // Entregas
    Route::prefix('entregas')
        ->name('deliveries')
        ->group(function () {

            // Marca uma entrega para cancelamento.
            Route::post('{delivery}/cancelar', CancelDeliveryController::class)
                ->name('.cancel');

            // Marca uma entrega para reagendamento.
            Route::post('{delivery}/reagendar', RescheduleDeliveryController::class)
                ->name('.reschedule');

            // Conclui todas as entregas conforme seu status.
            Route::post('finalizar', CompleteDeliveriesController::class)
                ->name('.complete');
        });
});

// Route::get('/test', function (\Illuminate\Http\Request $request) {
//     // dd(\App\Actions\Sector\FindSectorFromCep::run($request->get('cep')));
//     $testingTraits = new \App\Supports\TestingTraits();
// });

require __DIR__.'/auth.php';

app/Models/Order.php
<?php

namespace App\Models;

use App\Enums\OrderStatus;
use App\Models\Sector;
use App\Models\Campaign;
use App\Traits\Order\OrderStatusTrait;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Database\Eloquent\Factories\HasFactory;

class Order extends Model
{
    use HasFactory;
    use SoftDeletes;
    use OrderStatusTrait;

    const TABLE = 'orders';

    protected $fillable = [
        'id',
        'status',
        'cep',
        'phone_number',
        'address',
        'address_extra',
        'note',
        'consumer',
        'phone_number',
        'sector_id',
        'campaign_id',
        'created_at',
        'updated_at',
    ];

    protected $casts = [
        'status' => OrderStatus::class,
    ];

    // Relationships

    public function campaign()
    {
        return $this->belongsTo(Campaign::class);
    }

    public function sector()
    {
        return $this->belongsTo(Sector::class);
    }

    public function deliveries()
    {
        return $this->hasMany(Delivery::class);
    }

    // Queries

    public function lastDelivery()
    {
        return $this->deliveries()->latest()->first();
    }

    // Logics

    public function makeDeliveryUid()
    {
        return uniqid("{$this->id}|", true);
    }

    // Views

    public function formattedCep()
    {
        $cep = substr($this->cep, 0, 5) . '-' . substr($this->cep, 5, 3);

        return $cep;
    }

    public function fullAddress()
    {
        $address = [
            $this->address,
            $this->note,
            $this->address_extra,
            $this->formattedCep()
        ];

        return implode(' - ', array_filter($address));
    }

    public function lastDeliveryReason()
    {
        $delivery = $this->lastDelivery();

        if (!$delivery) return null;

        return $delivery->reason;
    }

    public function lastDeliveryUuid()
    {
        $delivery = $this->lastDelivery();

        if (!$delivery) return null;

        if (is_null($delivery->uber_uuid)) return null;

        $uberUuid = substr($delivery->uber_uuid, -5);

        return $uberUuid;
    }

    public function lastDeliveryTrackingUrl()
    {
        $delivery = $this->lastDelivery();

        if (!$delivery) return null;

        return $delivery->tracking_url;
    }
}

app/View/Components/GuestLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;
use Illuminate\View\View;

class GuestLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     */
    public function render(): View
    {
        return view('layouts.guest');
    }
}

resources/views/web/orders/details/processing.blade.php
{{-- CÓDIGO PARA VOLTAR NO CAMINHO DE PAO --}}
@php
    $currentUrl = url()->current(); // Obtém a URL atual
    $currentUrlWithoutTrailingSlash = preg_replace('/\/[^\/]*$/', '', $currentUrl); // Remove a última barra e o conteúdo após ela
@endphp

<x-guest-layout>
    @section('title', $campaign->title . ' - ' . __('order_status.' . $status->value))
    <x-header></x-header>
    <main class="group-detail-inner" id="top">
        <section class="intro">
            <div class="title">
                <div class="path">
                    <a href="{{ route('campaigns.index') }}">Todas as campanhas</a>
                    <a href="{{ route('campaigns.orders.index', $campaign->slug) }}">Pedidos - {{ $campaign->title }}</a>
                    <p>{{ __('order_status.' . $status->value) }}</p>
                </div>
                <div class="intro">
                    <h2>{{ $campaign->title }}</h2>
                </div>
            </div>
        </section>
        <div class="orders delivery">
            @include('web.orders.panels.processing', [
                'processingOrders' => collect($orders->items()),
                'processingCount' => $ordersCount,
                'detail' => true,
            ])
        </div>
        {{ $orders->appends(request()->query())->links('partials.my-paginate', ['paginator' => $orders]) }}
        <a class="up" href="#top"></a>
    </main>
    <x-footer></x-footer>
</x-guest-layout>

resources/views/web/orders/details/standard.blade.php
{{-- CÓDIGO PARA VOLTAR NO CAMINHO DE PAO --}}
@php
    $currentUrl = url()->current(); // Obtém a URL atual
    $currentUrlWithoutTrailingSlash = preg_replace('/\/[^\/]*$/', '', $currentUrl); // Remove a última barra e o conteúdo após ela
@endphp

<x-guest-layout>
    @section('title', $campaign->title . ' - ' . __('order_status.' . $status->value))
    <x-header></x-header>
    <main class="group-detail-inner" id="top">
        <section class="intro">
            <div class="title">
                <div class="path">
                    <a href="{{ route('campaigns.index') }}">Todas as campanhas</a>
                    <a href="{{ route('campaigns.orders.index', $campaign->slug) }}">Pedidos - {{ $campaign->title }}</a>
                    <p>{{ __('order_status.' . $status->value) }}</p>
                </div>
                <div class="intro">
                    <h2>{{ $campaign->title }}</h2>
                </div>
            </div>
        </section>
        <div class="orders {{ $status->value }}">
            <div class="title-orders">
                <h2>{{ __('order_status.' . $status->value) }}s</h2>
                <p>{{ TextHelper::formatNumber($ordersCount) }} {{ TextHelper::pluralize($ordersCount, 'pedido', 'pedidos') }}</p>
            </div>
            <div class="container-orders">
                <div class="intro-orders grid">
                    <h3>Nome</h3>
                    <h3>Endereço</h3>
                    <h3>Setor</h3>
                    {{-- <h3>Status</h3> --}}
                    <h3>Data</h3>
                </div>
                @if ($orders->isEmpty() === false)
                    @foreach ($orders as $order)
                        <div class="order-description grid">
                            <div class="content-container">
                                <p>{{ $order->consumer }}</p>
                            </div>
                            <div class="content-container">
                                <p>{{ $order->fullAddress() }}</p>
                            </div>
                            {{-- <div class="content-container">
                                <p>{{ $order->sector->name }}</p>
                            </div> --}}
                            <div class="content-container">
                                <span>{{ __('order_status.' . $status->value) }}</span>
                                @if ($order->isCanceled())
                                    <p>{{ $order->lastDeliveryReason() }}</p>
                                @endif
                            </div>
                            <div class="content-container">
                                <span>{{ $order->created_at->format('d/m/Y') }}</span>
                            </div>
                        </div>
                    @endforeach
                @else
                    <p class="notFound">Nenhum pedido</p>
                @endif
            </div>
        </div>
        {{ $orders->appends(request()->query())->links('partials.my-paginate', ['paginator' => $orders]) }}
        <a class="up" href="#top"></a>
    </main>
    <x-footer></x-footer>
</x-guest-layout>